Vagrant.configure("2") do |config|

    # main & default: normal OS series...
    config.vm.define "main", primary: true do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.network "private_network", ip: "10.0.0.10"

        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "wordpress.yml"
            ansible.sudo = true
        end
 
        node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
        end
    end

    config.vm.define "db" do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.network "private_network", ip: "10.0.0.20"

        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "db.yml"
            ansible.sudo = true
        end

        node.vm.provider "virtualbox" do |vb|
            ##vb.customize ["modifyvm", :id, "--memory", "256"]
        end
    end

end
