Vagrant.require_version ">= 1.8.1"

Vagrant.configure(2) do |config|

    config.vm.box = "williamyeh/ansible"
    config.vm.box_version = ">= 2.0.0"
    config.vm.hostname = "ANSIBLE"

    if Vagrant::Util::Platform.windows?
       # fix permission for using Windows as host machine
       config.vm.synced_folder "..", "/vagrant",
                               mount_options: ["dmode=775,fmode=664"]
    else
       config.vm.synced_folder "..", "/vagrant"
    end

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
        #vb.gui = true
    end

end
