- hosts: all
  become: true

  vars:
    hostname: mywordpress
    wordpress_version: 4.4.2
    wordpress_parent_path: /usr/share
    wordpress_path:        "{{ wordpress_parent_path }}/wordpress"
    wordpress_owner: www-data
    wordpress_group: www-data

  tasks:
    - name: ==> 0 - add host info
      lineinfile: dest=/etc/hosts line="10.0.0.10  {{ hostname }}" state=present


    - name: ==> 1 - add PPA of php7 (community)
      apt_repository: repo="ppa:ondrej/php"


    - debug: msg="==> 2 - add PPA of nginx (official)"

    - name: add Nginx stable repository (deb)
      apt_repository: >
        repo='deb http://nginx.org/packages/ubuntu/ trusty nginx'
        state=present

    - name: add Nginx stable repository (deb-src)
      apt_repository:
        repo: 'deb-src http://nginx.org/packages/ubuntu/ trusty nginx'
        state: present

    - name: add Nginx.org key
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present


    - name: ==> 3 - download/update the package lists
      apt: update_cache=yes



    - name: ==> 4 - install nginx, php-fpm, and php-mysql
      apt: name={{ item }} state=present
      with_items:
        - nginx
        - php7.0-fpm
        - php7.0-mysql


    - debug: msg="==> 5 - download and extract wordpress"

    # like wget, curl.
    #
    # Ansible 2.0 support extract with url.
    - name: download wordpress tarball
      get_url:
        url: "https://tw.wordpress.org/wordpress-{{ wordpress_version }}-zh_TW.tar.gz"
        dest: /tmp/

    - name: extract wordpress tarball
      unarchive:
        src: "/tmp/wordpress-{{ wordpress_version }}-zh_TW.tar.gz"
        dest: "{{ wordpress_parent_path }}"
        owner: "{{ wordpress_owner }}"
        group: "{{ wordpress_group }}"
        copy: no


    - debug: msg="==> 6 - install site conf file for wordpress"

    # check virtual default host file state.
    - name: check if "default.conf.bak" target exists
      stat: path=/etc/nginx/conf.d/default.conf
      register: filecheck

    # if filecheck is true, run this.
    - name: rename to "default.conf.bak", if any
      command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
      when: filecheck.stat.exists

    - name: copy wordpress site conf for nginx
      template:
        src: ./templates/nginx-wordpress.conf.j2
        dest: /etc/nginx/conf.d/nginx-wordpress.conf


    - debug: msg="==> 7 - change php-fpm unix socket permission to the same as nginx"

    - name: fix listen.owner for php-fpm
      lineinfile:
        dest: /etc/php/7.0/fpm/pool.d/www.conf
        regexp: '^listen.owner\s*=.*$'
        line: "listen.owner=nginx"
        state: present

    - name: fix listen.group for php-fpm
      lineinfile:
        dest: /etc/php/7.0/fpm/pool.d/www.conf
        regexp: '^listen.group\s*=.*$'
        line: "listen.group=nginx"
        state: present

    - name: restart php-fpm
      service: name=php7.0-fpm state=restarted
