- hosts: all
  sudo: true

  vars:
    hostname: mywordpress
    wordpress_install_url: "http://{{ hostname }}/wp-admin/install.php?step=2"
    blog_title: ANSIBLE_TEST
    blog_user: admin
    blog_password: admin
    blog_email: foo@gmail.com

  tasks:
    - debug: ==> 12 - automate the '5-minute install' process

    - name: install dependency - httplib2
      apt: name=python-httplib2 state=present
      #pip: name=httplib2

    - name: send POST to WordPress install wizard
      uri:
        url: "{{ wordpress_install_url }}"
        method: POST
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: "weblog_title={{ blog_title }}&user_name={{ blog_user }}&admin_email={{ blog_email }}&blog_public=true&admin_password={{ blog_password }}&admin_password2={{ blog_password }}"
        status_code: 200
