APP_SERVERS = [
    { :name => "app1", :ip => "10.0.0.30",
      :mem => "256"  , :box => "ubuntu/trusty64"
    },
    { :name => "app2", :ip => "10.0.0.31",
      :mem => "256"  , :box => "ubuntu/trusty64"
    },
    { :name => "app3", :ip => "10.0.0.32",
      :mem => "256"  , :box => "ubuntu/trusty64"
    }
]



Vagrant.configure("2") do |config|

    # main & default: normal OS series...
    config.vm.define "lb", primary: true do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.network "private_network", ip: "10.0.0.10"
        #node.vm.network "forwarded_port", guest: 1936, host: 1936

        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "lb.yml"
            ansible.sudo = true
        end

        node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
        end
    end


    # app servers
    APP_SERVERS.each do |opts|

        config.vm.define opts[:name] do |node|
            node.vm.box = opts[:box]
            node.vm.network "private_network", ip: opts[:ip]

            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", opts[:mem]]
            end

            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "wordpress.yml"
                ansible.sudo = true
            end
        end
    end


    # DB server
    config.vm.define "db" do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.network "private_network", ip: "10.0.0.20"

        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "db.yml"
            ansible.sudo = true
        end
    end

end
